# -*- coding: utf-8 -*-
"""Tarea 2.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aKtSF6xuvb7kZW9DWqbqNx1jSqRzGCs
"""

# --- Definición de Clases ---

class Numero:
    def __init__(self, valor):
        self.valor = valor

    def latex(self):
        return str(self.valor)

    def evaluar(self, variables=None):
        return self.valor

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

class Variable:
    def __init__(self, nombre):
        self.nombre = nombre

    def latex(self):
        # Corrección: se usa "\\" para representar una sola barra invertida
        if len(self.nombre) > 1:
            return "\\" + self.nombre
        return self.nombre

    def evaluar(self, variables=None):
        if variables and self.nombre in variables:
            return variables[self.nombre]
        else:
            raise ValueError(f"Variable '{self.nombre}' no definida.")

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

    def __radd__(self, otro): return Suma(otro, self)
    def __rsub__(self, otro): return Resta(otro, self)
    def __rmul__(self, otro): return Producto(otro, self)
    def __rpow__(self, otro): return Potencia(otro, self)

    def _repr_latex_(self):
        return f"$${self.latex()}$$"

class Suma:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def latex(self):
        # Implementación de latex() para Suma
        return "(" + self.izq.latex() + " + " + self.der.latex() + ")"

    def evaluar(self, variables=None):
        # Implementación de evaluar() para Suma
        return self.izq.evaluar(variables) + self.der.evaluar(variables)

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

    # Métodos dunder reversos para Suma
    def __radd__(self, otro): return Suma(otro, self)
    # No se definen __rsub__, __rmul__, __rpow__ aquí directamente para Suma,
    # ya que se aplican a los operandos individuales al construir la expresión.

    def _repr_latex_(self):
        # Mostramos la fórmula en LaTeX para visualización en notebooks
        return f"$${self.latex()}$$"

class Resta:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def latex(self):
        # Implementación de latex() para Resta
        return "(" + self.izq.latex() + " - " + self.der.latex() + ")"

    def evaluar(self, variables=None):
        # Implementación de evaluar() para Resta
        return self.izq.evaluar(variables) - self.der.evaluar(variables)

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    # Se añade __rsub__ para Resta
    def __rsub__(self, otro): return Resta(otro, self)
    def __mul__(self, otro): return Producto(self, otro)
    def __pow__(self, otro): return Potencia(self, otro)

    def _repr_latex_(self):
        # Mostramos la fórmula en LaTeX para visualización en notebooks
        return f"$${self.latex()}$$"

class Producto:
    def __init__(self, izq, der):
        self.izq = Numero(izq) if isinstance(izq, (int, float)) else izq
        self.der = Numero(der) if isinstance(der, (int, float)) else der

    def latex(self):
        # Implementación de latex() para Producto
        return "(" + self.izq.latex() + " \\cdot " + self.der.latex() + ")"

    def evaluar(self, variables=None):
        # Implementación de evaluar() para Producto
        return self.izq.evaluar(variables) * self.der.evaluar(variables)

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    # Se añade __rmul__ para Producto
    def __rmul__(self, otro): return Producto(otro, self)
    def __pow__(self, otro): return Potencia(self, otro)

    def _repr_latex_(self):
        # Mostramos la fórmula en LaTeX para visualización en notebooks
        return f"$${self.latex()}$$"

class Potencia:
    def __init__(self, base, exponente):
        self.base = Numero(base) if isinstance(base, (int, float)) else base
        self.exp = Numero(exponente) if isinstance(exponente, (int, float)) else exponente

    def latex(self):
        # Implementación de latex() para Potencia
        # Usamos llaves {} para el exponente en LaTeX
        return "{" + self.base.latex() + "}^{" + self.exp.latex() + "}"

    def evaluar(self, variables=None):
        # Implementación de evaluar() para Potencia
        return self.base.evaluar(variables) ** self.exp.evaluar(variables)

    def __add__(self, otro): return Suma(self, otro)
    def __sub__(self, otro): return Resta(self, otro)
    def __mul__(self, otro): return Producto(self, otro)
    def __rmul__(self, otro): return Producto(otro, self)
    def __pow__(self, otro): return Potencia(self, otro)

    # Métodos dunder reversos para Potencia
    # __rpow__ es para operaciones como `2 ** self.base`
    def __rpow__(self, otro): return Potencia(otro, self)

    def _repr_latex_(self):
        # Mostramos la fórmula en LaTeX para visualización en notebooks
        return f"$${self.latex()}$$"

# --- Ejemplo de Prueba ---

x = Variable("x")
y = Variable("alpha") # Variable con nombre de más de una letra

expr = (x + 2) * (y - 5)**2

# Visualizar la expresión en LaTeX (se imprime la cadena LaTeX)
print(f"Representación LaTeX de la expresión: {expr.latex()}")
# O para ver cómo se renderizaría en un notebook:
print(f"Visualización LaTeX: {expr._repr_latex_()}")

# Evaluar con x = 10, alpha = 8
try:
    resultado = expr.evaluar({'x': 10, 'alpha': 8})
    print(f"Valor numérico (para x=10, alpha=8): {resultado}")
except ValueError as e:
    print(f"Error de evaluación: {e}")